server:
  port: ${SERVER_PORT}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
  kafka:
    topic:
      name: ${TOPIC_NAME}
    consumer:
      group-id: email
      auto-offset-reset: earliest
      bootstrap-servers: ${KAFKA_HOST}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"